
import { GoogleGenAI } from "@google/genai";

// Helper to ensure we always use a fresh instance and the latest API key
const getAi = () => new GoogleGenAI({ apiKey: process.env.API_KEY });

/**
 * Reimagines a room based on an original image and a chosen style.
 */
export async function redesignRoom(imageB64: string, stylePrompt: string): Promise<string> {
  const ai = getAi();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/jpeg',
            data: imageB64.split(',')[1] || imageB64,
          },
        },
        {
          text: `Transform this room following this description: ${stylePrompt}. Maintain the basic architecture but completely update the furniture, colors, and decor.`,
        },
      ],
    },
  });

  // Fixed: Iterating through parts to find the image part as per guidelines
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image generated by the AI");
}

/**
 * Refines a design based on chat input.
 */
export async function refineDesign(originalB64: string, currentB64: string, instruction: string): Promise<string> {
  const ai = getAi();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: 'image/jpeg',
            data: originalB64.split(',')[1],
          },
        },
        {
          inlineData: {
            mimeType: 'image/jpeg',
            data: currentB64.split(',')[1],
          },
        },
        {
          text: `The first image is the original room. The second image is a redesign. Please update the second image according to this instruction: "${instruction}". Keep the rest of the redesign consistent.`,
        },
      ],
    },
  });

  // Fixed: Iterating through parts to find the image part
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("Failed to refine design");
}

/**
 * Gets product recommendations and links using Google Search grounding.
 */
export async function getProductRecommendations(roomImageB64: string, query: string) {
  const ai = getAi();
  // Fixed: Upgraded to gemini-3-pro-image-preview for real-time information with search when image context is present.
  const response = await ai.models.generateContent({
    model: 'gemini-3-pro-image-preview',
    contents: {
      parts: [
        {
            inlineData: {
              mimeType: 'image/jpeg',
              data: roomImageB64.split(',')[1],
            },
        },
        { text: `Identify the main furniture items in this redesigned room and provide shoppable links or product names for similar items. User asked: ${query}` }
      ]
    },
    config: {
      tools: [{ googleSearch: {} }],
    },
  });

  // Fixed: Accessing the .text property directly
  const text = response.text || "I've identified some items for you.";
  const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks || [];
  
  const links = chunks
    .filter(chunk => chunk.web)
    .map(chunk => ({
      title: chunk.web?.title || 'Product Link',
      uri: chunk.web?.uri || '#'
    }));

  return { text, links };
}
